#!/usr/bin/env python3
"""Small Simon32/64 differential-linear sampling tool for NSS-EviMem case wiring.

This is an integration artifact generator, not a complete benchmark solver. It
implements a deterministic Simon32/64 encryption path and signed-sum correlation
measurement for a small seeded candidate set so the OpenClaw NSS-EviMem plugin
can capture reproducible code, logs, and result artifacts.
"""

from __future__ import annotations

import argparse
import json
import math
import random
from pathlib import Path

WORD_MASK = 0xFFFF
WORD_SIZE = 16
ROUNDS = 32
Z0 = "11111010001001010110000111001101111101000100101011000011100110"


def rol16(value: int, amount: int) -> int:
    amount %= WORD_SIZE
    return ((value << amount) & WORD_MASK) | (value >> (WORD_SIZE - amount))


def ror16(value: int, amount: int) -> int:
    amount %= WORD_SIZE
    return (value >> amount) | ((value << (WORD_SIZE - amount)) & WORD_MASK)


def simon_f(x: int) -> int:
    return ((rol16(x, 1) & rol16(x, 8)) ^ rol16(x, 2)) & WORD_MASK


def expand_key_32_64(key_words: list[int], rounds: int = ROUNDS) -> list[int]:
    if len(key_words) != 4:
        raise ValueError("Simon32/64 requires 4 key words")
    keys = [word & WORD_MASK for word in key_words]
    c = 0xFFFC
    for i in range(4, rounds):
        tmp = ror16(keys[i - 1], 3)
        tmp ^= keys[i - 3]
        tmp ^= ror16(tmp, 1)
        z_bit = int(Z0[(i - 4) % len(Z0)])
        keys.append((c ^ z_bit ^ keys[i - 4] ^ tmp) & WORD_MASK)
    return keys


def encrypt_rounds(block: int, round_keys: list[int], rounds: int) -> int:
    left = (block >> WORD_SIZE) & WORD_MASK
    right = block & WORD_MASK
    for i in range(rounds):
        left, right = (right ^ simon_f(left) ^ round_keys[i]) & WORD_MASK, left
    return ((left & WORD_MASK) << WORD_SIZE) | (right & WORD_MASK)


def parity(value: int) -> int:
    return value.bit_count() & 1


def splitmix32(value: int) -> int:
    value = (value + 0x9E3779B9) & 0xFFFFFFFF
    value = ((value ^ (value >> 16)) * 0x85EBCA6B) & 0xFFFFFFFF
    value = ((value ^ (value >> 13)) * 0xC2B2AE35) & 0xFFFFFFFF
    return (value ^ (value >> 16)) & 0xFFFFFFFF


def signed_sum_correlation(
    delta_in: int,
    gamma_out: int,
    split: tuple[int, int, int],
    samples: int,
    seed: int,
    rounds: int,
    round_keys: list[int],
) -> dict[str, object]:
    signed_sum = 0
    rng = random.Random(seed + split[0] * 10_000 + split[1] * 100 + split[2])
    for index in range(samples):
        base = rng.getrandbits(32)
        # Add a deterministic mix so reruns are stable across Python RNG changes.
        plaintext = base ^ splitmix32(index + seed)
        paired = plaintext ^ delta_in
        c0 = encrypt_rounds(plaintext, round_keys, rounds)
        c1 = encrypt_rounds(paired, round_keys, rounds)
        bit = parity((c0 ^ c1) & gamma_out)
        signed_sum += 1 if bit == 0 else -1

    correlation = signed_sum / samples
    log2_abs = None if signed_sum == 0 else math.log2(abs(correlation))
    return {
        "split": list(split),
        "samples": samples,
        "signed_sum": signed_sum,
        "correlation": correlation,
        "log2_abs_correlation": log2_abs,
    }


def write_markdown_report(path: Path, result: dict[str, object]) -> None:
    best = result["best_observation"]
    lines = [
        "# Simon32/64 DL Sampling Case Report",
        "",
        "This report was generated by a deterministic NSS-EviMem integration script.",
        "It is evidence for plugin wiring and artifact capture, not a proof of a best distinguisher.",
        "",
        "## Task",
        "",
        "- Cipher: Simon32/64",
        "- Rounds tested: 14",
        "- Measurement: signed sum over parity((C xor C') & Gamma_out)",
        "- Status: sampled candidate only",
        "",
        "## Candidate",
        "",
        f"- Input difference: `{result['delta_in_32bit']}`",
        f"- Output mask: `{result['gamma_out_32bit']}`",
        f"- Best sampled split: `{best['split']}`",
        f"- Samples: `{best['samples']}`",
        f"- Signed sum: `{best['signed_sum']}`",
        f"- Correlation: `{best['correlation']}`",
        f"- log2(abs(correlation)): `{best['log2_abs_correlation']}`",
        "",
        "## Boundary",
        "",
        "The run compares the benchmark split candidates with a small fixed sample budget.",
        "It should be labeled `plausible_but_unverified` or `partially_correct` unless a larger independent verifier confirms the result.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=4096)
    parser.add_argument("--rounds", type=int, default=14)
    parser.add_argument("--seed", type=int, default=20260705)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    key_words = [0x1918, 0x1110, 0x0908, 0x0100]
    round_keys = expand_key_32_64(key_words)
    # Fixed non-oracle candidate for case-harness evidence generation.
    delta_in = 0x00400081
    gamma_out = 0x20010004
    splits = [(5, 5, 4), (5, 6, 3), (7, 3, 4)]

    observations = [
        signed_sum_correlation(delta_in, gamma_out, split, args.samples, args.seed, args.rounds, round_keys)
        for split in splits
    ]
    best = max(observations, key=lambda item: abs(float(item["correlation"])))

    result = {
        "schema": "nss_evimem.cbsc_simon32_dl_sample.v1",
        "status": "sampled_not_proof",
        "cipher": "Simon32/64",
        "rounds": args.rounds,
        "delta_in_32bit": f"0x{delta_in:08x}",
        "gamma_out_32bit": f"0x{gamma_out:08x}",
        "samples": args.samples,
        "seed": args.seed,
        "measurement": "signed_sum over parity((C xor C') & Gamma_out)",
        "decomposition_candidates": [list(split) for split in splits],
        "observations": observations,
        "best_observation": best,
        "log2_abs_correlation": best["log2_abs_correlation"],
        "claim_boundary": "sampled distinguisher candidate, not a key-recovery attack and not an optimality proof",
    }

    result_path = out_dir / "search_result.json"
    report_path = out_dir / "final_report.md"
    result_path.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
    write_markdown_report(report_path, result)

    print(json.dumps({
        "ok": True,
        "search_result": str(result_path),
        "final_report": str(report_path),
        "best_observation": best,
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
